# Generated by Django 3.2.12 on 2022-06-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cresent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
